In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

import matplotlib as mpl
import seaborn as sns

import time
from functools import wraps
#import pysnooper


def fn_timer(function):
  @wraps(function)
  def function_timer(*args, **kwargs):
    t0 = time.time()
    result = function(*args, **kwargs)
    t1 = time.time()
    print ("Total time running %s: %s seconds" %
        (function.__name__, str(t1-t0)))
    return result
  return function_timer

%matplotlib inline
dataset = pd.read_csv("Dataset/trainData/ANTIF_TRAIN_SET.csv",header=0,index_col=0)
dataset_x=dataset.drop(['target'],axis=1)
dataset_y=dataset['target']

# 1.数据平衡

## 1.1下采样

In [32]:
df_y0=dataset_y[dataset_y==0].iloc[0:12000]
df_y1=dataset_y[dataset_y==1]
df_x0=dataset_x[dataset_y==0].iloc[0:12000]
df_x1=dataset_x[dataset_y==1]
dataset_x=pd.concat([df_x0,df_x1],axis=0)
dataset_y=pd.concat([df_y0,df_y1],axis=0)

## 1.2 SMOTE

In [2]:
from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=0)
X_train,Y_train=sm.fit_sample(dataset_x,dataset_y)
dataset_x=pd.DataFrame(X_train)
dataset_y=pd.Series(Y_train)
dataset_x

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
D:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
D:\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
0,20.714600,11.888600,25.688800,21.358800,23.962400,10.511600,10.177200,33.077800,-13.858000,14.610200,...,-9.678000,13.723000,7.713000,5.189600,39.681600,1.627800,23.390400,16.100400,34.245600,10.780200
1,30.888400,-10.093400,29.453800,11.155000,26.430400,25.639600,13.893800,29.153200,-4.858000,11.888400,...,-6.649800,16.214600,6.589200,15.120600,47.105000,-0.090800,12.103000,17.433000,42.729400,-16.304800
2,15.447000,-8.196800,22.189400,20.637000,20.638400,-6.190600,8.757600,35.992800,8.224400,15.238600,...,3.549200,11.404200,7.120600,1.699200,33.254200,-3.256400,19.630600,18.759600,36.206400,4.778800
3,21.939800,4.844800,22.932000,4.595600,21.850000,-20.696800,11.487600,45.099000,11.154200,15.623800,...,5.557200,17.204400,1.158600,-5.908000,34.386000,-0.273800,18.083000,16.430000,21.113200,14.748200
4,17.767400,-7.403000,25.374200,11.220800,19.328600,-15.912800,9.991600,39.823800,4.479800,12.262600,...,-6.723000,15.754200,3.260200,-0.734200,38.398200,2.525400,-5.477000,20.054400,34.688800,7.886600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215877,15.154505,6.178069,17.131955,18.877207,24.951825,-8.756503,11.194837,38.751188,7.284322,14.191209,...,2.638259,10.829574,2.210167,-1.392094,36.656864,-0.211282,16.668162,19.299670,32.232457,-6.470230
215878,21.940112,-3.156247,29.791471,9.153509,20.618716,-35.152998,11.712217,46.885452,3.008909,13.325238,...,10.698589,15.641674,1.367620,2.915373,30.782204,0.746368,3.600909,17.723316,38.534063,-3.477243
215879,24.508425,2.643888,23.807777,17.743354,23.735711,-19.606799,11.339284,43.979744,11.356691,12.056339,...,-2.979440,22.725493,5.294265,14.279728,42.045007,-0.626677,-11.712653,17.150523,22.741622,6.866377
215880,15.628239,7.299241,23.997899,11.608186,22.039767,-6.998473,10.453140,41.638409,-5.499788,13.375962,...,12.808731,19.017139,2.059068,11.094154,38.119399,1.967367,-0.596695,15.749688,26.436437,4.287300
215881,26.084683,3.069470,22.225717,20.107847,25.470619,-23.364269,10.288161,36.987292,1.213131,15.616372,...,9.700570,12.880504,0.696526,18.790805,39.245599,-1.590931,6.151838,18.702759,27.784740,4.444747

# 2.分箱
对应的分箱方法：
A. 无监督： (1) 等宽 (2) 等频  (3) 聚类

B. 有监督 (1) 卡方分箱法(ChiMerge)  (2) ID3、C4.5、CART等单变量决策树算法  (3)  信用评分建模的IV最大化分箱 等

以下基于CART算法对连续变量进行最优分箱

由于CART是决策树分类算法，所以相当于是单变量决策树分类。

简单介绍下理论：

CART是二叉树，每次仅进行二元分类，对于连续性变量，方法是依次计算相邻两元素值的中位数，将数据集一分为二，计算该点作为切割点时的基尼值较分割前的基尼值下降程度，每次切分时，选择基尼下降程度最大的点为最优切分点，再将切分后的数据集按同样原则切分，直至终止条件为止。

关于CART分类的终止条件：视实际情况而定，以下设置为 a.每个叶子节点的样本量>=总样本量的5%   b.内部节点再划分所需的最小样本数>=总样本量的10%

## 2.1 CART分箱

In [ ]:
def calc_score_median(sample_set, var):
    '''
    计算相邻评分的中位数，以便进行决策树二元切分
    param sample_set: 待切分样本
    param var: 分割变量名称
    '''
    var_list = list(np.unique(sample_set[var]))
    var_median_list = []
    for i in range(len(var_list) -1):
        var_median = (var_list[i] + var_list[i+1]) / 2
        var_median_list.append(var_median)
    return var_median_list

#var表示需要进行分箱的变量名，返回一个样本变量中位数的list
def choose_best_split(sample_set, var, min_sample):
    '''
    使用CART分类决策树选择最好的样本切分点
    返回切分点
    param sample_set: 待切分样本
    param var: 分割变量名称
    param min_sample: 待切分样本的最小样本量(限制条件)
    '''
    # 根据样本评分计算相邻不同分数的中间值
    score_median_list = calc_score_median(sample_set, var)
    median_len = len(score_median_list)
    sample_cnt = sample_set.shape[0]
    sample1_cnt = sum(sample_set['target'])
    sample0_cnt =  sample_cnt- sample1_cnt
    Gini = 1 - np.square(sample1_cnt / sample_cnt) - np.square(sample0_cnt / sample_cnt)
    
    bestGini = 0.0; bestSplit_point = 0.0; bestSplit_position = 0.0
    for i in range(median_len):
        left = sample_set[sample_set[var] < score_median_list[i]]
        right = sample_set[sample_set[var] > score_median_list[i]]
        
        left_cnt = left.shape[0]; right_cnt = right.shape[0]
        left1_cnt = sum(left['target']); right1_cnt = sum(right['target'])
        left0_cnt =  left_cnt - left1_cnt; right0_cnt =  right_cnt - right1_cnt
        left_ratio = left_cnt / sample_cnt; right_ratio = right_cnt / sample_cnt
        
        if left_cnt < min_sample or right_cnt < min_sample:
            continue
        
        Gini_left = 1 - np.square(left1_cnt / left_cnt) - np.square(left0_cnt / left_cnt)
        Gini_right = 1 - np.square(right1_cnt / right_cnt) - np.square(right0_cnt / right_cnt)
        Gini_temp = Gini - (left_ratio * Gini_left + right_ratio * Gini_right)
        if Gini_temp > bestGini:
            bestGini = Gini_temp; bestSplit_point = score_median_list[i]
            if median_len > 1:
                bestSplit_position = i / (median_len - 1)
            else:
                bestSplit_position = i / median_len
        else:
            continue
               
    Gini = Gini - bestGini
    return bestSplit_point, bestSplit_position

#min_sample 参数为最小叶子节点的样本阈值，如果小于该阈值则不进行切分，如前面所述设置为整体样本量的5%
#返回的结果我这里只返回了最优分割点，如果需要返回其他的比如GINI值，可以自行添加。
def bining_data_split(sample_set, var, min_sample, split_list):
    '''
    划分数据找到最优分割点list
    param sample_set: 待切分样本
    param var: 分割变量名称
    param min_sample: 待切分样本的最小样本量(限制条件)
    param split_list: 最优分割点list
    '''
    split, position = choose_best_split(sample_set, var, min_sample)
    if split != 0.0:
        split_list.append(split)
    # 根据分割点划分数据集，继续进行划分
    sample_set_left = sample_set[sample_set[var] < split]
    sample_set_right = sample_set[sample_set[var] > split]
    # 如果左子树样本量超过2倍最小样本量，且分割点不是第一个分割点，则切分左子树
    if len(sample_set_left) >= min_sample * 2 and position not in [0.0, 1.0]:
        bining_data_split(sample_set_left, var, min_sample, split_list)
    else:
        None
    # 如果右子树样本量超过2倍最小样本量，且分割点不是最后一个分割点，则切分右子树
    if len(sample_set_right) >= min_sample * 2 and position not in [0.0, 1.0]:
        bining_data_split(sample_set_right, var, min_sample, split_list)
    else:
        None
        
#split_list 参数是用来保存返回的切分点，每次切分后返回的切分点存入该list
#在这里判断切分点分割的左子树和右子树是否满足“内部节点再划分所需的最小样本数>=总样本量的10%”的条件，
#如果满足则进行递归调用。
@fn_timer
def get_bestsplit_list(sample_set, var):
    '''
    根据分箱得到最优分割点list
    param sample_set: 待切分样本
    param var: 分割变量名称
    '''
    # 计算最小样本阈值（终止条件）
    min_df = sample_set.shape[0] * 0.05
    split_list = []
    # 计算第一个和最后一个分割点
    bining_data_split(sample_set, var, min_df, split_list)
    return split_list


split_list=get_bestsplit_list(dataset,['attr_0'])
split_list

## 2.2 等宽分箱
https://www.cnblogs.com/sench/p/10128216.html

In [3]:

for i in dataset_x.columns:
    dataset_x.iloc[:,i]=pd.cut(dataset_x.iloc[:,i],5,retbins=False)
dataset_x

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
0,"(16.742, 24.705]","(10.586, 20.754]","(24.959, 31.833]","(21.118, 26.377]","(19.427, 24.066]","(-3.12, 15.692]","(9.575, 12.015]","(28.573, 37.51]","(-21.051, -12.967]","(13.685, 16.557]",...,"(-15.212, -2.238]","(10.536, 18.147]","(7.031, 11.918]","(0.083, 11.908]","(32.776, 40.47]","(1.004, 4.775]","(22.891, 35.368]","(14.337, 16.753]","(28.837, 36.611]","(1.959, 28.513]"
1,"(24.705, 32.667]","(-19.919, -9.751]","(24.959, 31.833]","(10.602, 15.86]","(24.066, 28.704]","(15.692, 34.503]","(12.015, 14.455]","(28.573, 37.51]","(-4.922, 3.122]","(10.813, 13.685]",...,"(-15.212, -2.238]","(10.536, 18.147]","(2.145, 7.031]","(11.908, 23.733]","(40.47, 48.164]","(-2.767, 1.004]","(10.414, 22.891]","(16.753, 19.169]","(36.611, 44.384]","(-24.596, 1.959]"
2,"(8.779, 16.742]","(-9.751, 0.417]","(18.086, 24.959]","(15.86, 21.118]","(19.427, 24.066]","(-21.931, -3.12]","(7.135, 9.575]","(28.573, 37.51]","(3.122, 11.166]","(13.685, 16.557]",...,"(-2.238, 10.736]","(10.536, 18.147]","(7.031, 11.918]","(0.083, 11.908]","(32.776, 40.47]","(-6.538, -2.767]","(10.414, 22.891]","(16.753, 19.169]","(28.837, 36.611]","(1.959, 28.513]"
3,"(16.742, 24.705]","(0.417, 10.586]","(18.086, 24.959]","(0.0597, 5.344]","(19.427, 24.066]","(-21.931, -3.12]","(9.575, 12.015]","(37.51, 46.447]","(3.122, 11.166]","(13.685, 16.557]",...,"(-2.238, 10.736]","(10.536, 18.147]","(-2.742, 2.145]","(-11.742, 0.083]","(32.776, 40.47]","(-2.767, 1.004]","(10.414, 22.891]","(14.337, 16.753]","(21.063, 28.837]","(1.959, 28.513]"
4,"(16.742, 24.705]","(-9.751, 0.417]","(24.959, 31.833]","(10.602, 15.86]","(14.788, 19.427]","(-21.931, -3.12]","(9.575, 12.015]","(37.51, 46.447]","(3.122, 11.166]","(10.813, 13.685]",...,"(-15.212, -2.238]","(10.536, 18.147]","(2.145, 7.031]","(-11.742, 0.083]","(32.776, 40.47]","(1.004, 4.775]","(-14.54, -2.063]","(19.169, 21.585]","(28.837, 36.611]","(1.959, 28.513]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215877,"(8.779, 16.742]","(0.417, 10.586]","(11.212, 18.086]","(15.86, 21.118]","(24.066, 28.704]","(-21.931, -3.12]","(9.575, 12.015]","(37.51, 46.447]","(3.122, 11.166]","(13.685, 16.557]",...,"(-2.238, 10.736]","(10.536, 18.147]","(2.145, 7.031]","(-11.742, 0.083]","(32.776, 40.47]","(-2.767, 1.004]","(10.414, 22.891]","(19.169, 21.585]","(28.837, 36.611]","(-24.596, 1.959]"
215878,"(16.742, 24.705]","(-9.751, 0.417]","(24.959, 31.833]","(5.344, 10.602]","(19.427, 24.066]","(-40.743, -21.931]","(9.575, 12.015]","(46.447, 55.384]","(-4.922, 3.122]","(10.813, 13.685]",...,"(-2.238, 10.736]","(10.536, 18.147]","(-2.742, 2.145]","(0.083, 11.908]","(25.083, 32.776]","(-2.767, 1.004]","(-2.063, 10.414]","(16.753, 19.169]","(36.611, 44.384]","(-24.596, 1.959]"
215879,"(16.742, 24.705]","(0.417, 10.586]","(18.086, 24.959]","(15.86, 21.118]","(19.427, 24.066]","(-21.931, -3.12]","(9.575, 12.015]","(37.51, 46.447]","(11.166, 19.211]","(10.813, 13.685]",...,"(-15.212, -2.238]","(18.147, 25.758]","(2.145, 7.031]","(11.908, 23.733]","(40.47, 48.164]","(-2.767, 1.004]","(-14.54, -2.063]","(16.753, 19.169]","(21.063, 28.837]","(1.959, 28.513]"
215880,"(8.779, 16.742]","(0.417, 10.586]","(18.086, 24.959]","(10.602, 15.86]","(19.427, 24.066]","(-21.931, -3.12]","(9.575, 12.015]","(37.51, 46.447]","(-12.967, -4.922]","(10.813, 13.685]",...,"(10.736, 23.71]","(18.147, 25.758]","(-2.742, 2.145]","(0.083, 11.908]","(32.776, 40.47]","(1.004, 4.775]","(-2.063, 10.414]","(14.337, 16.753]","(21.063, 28.837]","(1.959, 28.513]"
215881,"(24.705, 32.667]","(0.417, 10.586]","(18.086, 24.959]","(15.86, 21.118]","(24.066, 28.704]","(-40.743, -21.931]","(9.575, 12.015]","(28.573, 37.51]","(-4.922, 3.122]","(13.685, 16.557]",...,"(-2.238, 10.736]","(10.536, 18.147]","(-2.742, 2.145]","(11.908, 23.733]","(32.776, 40.47]","(-2.767, 1.004]","(-2.063, 10.414]","(16.753, 19.169]","(21.063, 28.837]","(1.959, 28.513]"

# 3.one-hot

In [4]:
dataset_x=pd.get_dummies(dataset_x)

# 训练数据保存

In [6]:
dataset_x.to_csv("Dataset/trainData/ANTIF_TRAIN_SET_(分桶+onehot+平衡).csv")
pd.read_csv("Dataset/trainData/ANTIF_TRAIN_SET_(分桶+onehot+平衡).csv",header=0,index_col=0)

,"0_(0.777, 8.779]","0_(8.779, 16.742]","0_(16.742, 24.705]","0_(24.705, 32.667]","0_(32.667, 40.63]","1_(-30.138, -19.919]","1_(-19.919, -9.751]","1_(-9.751, 0.417]","1_(0.417, 10.586]","1_(10.586, 20.754]",...,"198_(13.251, 21.063]","198_(21.063, 28.837]","198_(28.837, 36.611]","198_(36.611, 44.384]","198_(44.384, 52.158]","199_(-77.838, -51.151]","199_(-51.151, -24.596]","199_(-24.596, 1.959]","199_(1.959, 28.513]","199_(28.513, 55.068]"
0,0,0,1,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,1,0
1,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
2,0,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0
3,0,0,1,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,0,0,1,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215877,0,1,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
215878,0,0,1,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0
215879,0,0,1,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
215880,0,1,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
215881,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0